# Sintaxis Básica

In [1]:
import tensorflow as tf

Verificar versión:

In [2]:
print(tf.__version__)

1.13.0-rc1


## Tensor

In [3]:
hello = tf.constant('Hola a todos')

In [4]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [5]:
print(type(hello))

<class 'tensorflow.python.framework.ops.Tensor'>


In [6]:
world = tf.constant('world')

In [7]:
result = hello + world

In [8]:
print(result)

Tensor("add:0", shape=(), dtype=string)


In [9]:
with tf.Session() as sess:
    print(sess.run(result))

b'Hola a todosworld'


Otro ejemplo

In [10]:
tensor1 = tf.constant(2.5)
tensor2 = tf.constant(7.8)
print(tensor1)
print(tensor2)

Tensor("Const_2:0", shape=(), dtype=float32)
Tensor("Const_3:0", shape=(), dtype=float32)


In [11]:
tensor3 = tensor1 + tensor2

In [12]:
with tf.Session() as sess:
    x = sess.run(tensor3)

In [13]:
print(x)

10.3


## Operaciones

In [14]:
const1 = tf.constant(10)
const2 = tf.constant(25)

In [15]:
val1 = const1 + const2

In [17]:
fill_mat = tf.fill((4,4), 23)
myzeros = tf.zeros((5,5))
myones = tf.ones((2,2))
myrandn = tf.random_normal((4,4),mean=0,stddev=0.5)
myrandu = tf.random_uniform((3,3),  minval=0.0, maxval=1.0)

In [18]:
print(myones)

Tensor("ones_1:0", shape=(2, 2), dtype=float32)


## Sesión Interactiva

In [19]:
sess = tf.InteractiveSession()

In [20]:
print(myrandn)

Tensor("random_normal:0", shape=(4, 4), dtype=float32)


In [21]:
print(myrandn.eval())

[[ 0.24584271 -0.1991671   0.26905364  0.25085604]
 [-0.18357462 -0.47154787  0.36939132 -0.7084595 ]
 [-0.14272124 -0.73530054 -0.7032243  -0.31960785]
 [ 0.48716912  0.83442897  0.9257511  -0.1776716 ]]


In [22]:
print(val1.eval())

35


## Multiplicación de matrices

In [23]:
a = tf.constant([ [1,2], [3,4] ])

In [24]:
print(a)

Tensor("Const_6:0", shape=(2, 2), dtype=int32)


In [25]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [26]:
b = tf.constant([ [10], [100] ])
print(b.get_shape())

(2, 1)


In [27]:
result = a * b
result.eval()

array([[ 10,  20],
       [300, 400]], dtype=int32)